import { Hono } from 'hono'
import { z } from 'zod'
import { zValidator } from '@hono/zod-validator'
import { prisma } from '../../lib/prisma.js'
import { openrouterChat } from '../../services/openrouter.js'
import { runDuplicateDetection } from '../../services/duplicateDetection.js'

const app = new Hono()

const MODELS = [
  // OpenAI
  'openai/gpt-4o-mini',
  'openai/gpt-4o',
  // Anthropic
  'anthropic/claude-3-5-haiku',
  'anthropic/claude-3-7-sonnet',
  // Google Gemini (current generation)
  'google/gemini-2.5-pro-preview',
  'google/gemini-2.0-flash',
  'google/gemini-2.0-flash-lite',
  // DeepSeek
  'deepseek/deepseek-chat',
  'deepseek/deepseek-r1',
  // Qwen
  'qwen/qwen-2.5-72b-instruct',
  'qwen/qwen-turbo',
  // Meta
  'meta-llama/llama-3.3-70b-instruct',
  'meta-llama/llama-3.1-8b-instruct',
]

app.get('/models', async (c) => {
  return c.json(MODELS)
})

app.get('/tasks', async (c) => {
  const tasks = await prisma.aiTask.findMany({ orderBy: { createdAt: 'desc' }, take: 50 })
  return c.json(tasks)
})

app.get('/tasks/:id', async (c) => {
  const task = await prisma.aiTask.findUnique({ where: { id: c.req.param('id') } })
  if (!task) return c.json({ error: 'Not found' }, 404)
  return c.json(task)
})

// Generate questions via AI
app.post(
  '/generate',
  zValidator('json', z.object({
    model: z.string(),
    count: z.number().int().min(1).max(20).default(5),
    category: z.string().optional(),
    difficulty: z.enum(['EASY', 'MEDIUM', 'HARD']).optional(),
    type: z.enum(['STANDARD', 'MULTIPLE_CHOICE', 'MULTIPLE_ANSWER']).default('STANDARD'),
    instructions: z.string().optional(),
  })),
  async (c) => {
    if (!process.env.OPEN_ROUTER_API_KEY) {
      return c.json({ error: 'OPEN_ROUTER_API_KEY not configured' }, 503)
    }

    const body = c.req.valid('json')

    const task = await prisma.aiTask.create({
      data: { type: 'generate', status: 'running', model: body.model, prompt: JSON.stringify(body) },
    })

    // Run async (don't await in request, update task when done)
    ;(async () => {
      try {
        const typeInstructions: Record<string, string> = {
          STANDARD: 'Each question should have a single correct free-text answer.',
          MULTIPLE_CHOICE: 'Each question should have exactly 4 options (A-D), with exactly one correct answer. Mark the correct answer with isCorrect:true, the rest with isCorrect:false.',
          MULTIPLE_ANSWER: `Each question asks players to name N items from a larger set of valid answers.
CRITICAL: You MUST list ALL valid answers in the answers array — not just the N that the question asks for.
Example: "Name 3 of the 5 oceans" — the question only requires 3 answers, but you must provide all 5 oceans in the answers array, each with isCorrect:true.
Example: "Name 3 primary colors" — there are exactly 3 primary colors, so list all 3.
Example: "Name 3 elements that are noble gases" — there are 7 noble gases; list all 7 in the answers array.
This is essential because all valid answers must be available for fair scoring.
Phrase the question as "Name [N] of the [category]..." to make clear that more valid answers exist than required.`,
        }

        const prompt = `Generate exactly ${body.count} trivia questions${body.category ? ` about ${body.category}` : ''} at ${body.difficulty ?? 'MEDIUM'} difficulty.
Type: ${body.type}. ${typeInstructions[body.type]}
${body.instructions ? `Additional instructions: ${body.instructions}` : ''}

Respond ONLY with a valid JSON array. Each element must have:
- "text": the question text
- "answers": array of objects with "text" (string), "isCorrect" (boolean), "order" (number)
- "category": string
- "difficulty": "EASY"|"MEDIUM"|"HARD"

Example for MULTIPLE_CHOICE:
[{"text":"Which planet is largest?","answers":[{"text":"Jupiter","isCorrect":true,"order":0},{"text":"Saturn","isCorrect":false,"order":1},{"text":"Earth","isCorrect":false,"order":2},{"text":"Mars","isCorrect":false,"order":3}],"category":"Science","difficulty":"EASY"}]`

        const content = await openrouterChat(body.model, [{ role: 'user', content: prompt }])

        // Extract JSON from response
        const jsonMatch = content.match(/\[[\s\S]*\]/)
        if (!jsonMatch) throw new Error('No JSON array found in response')
        const generated = JSON.parse(jsonMatch[0]) as any[]

        // Create staged questions
        const staged = await Promise.all(
          generated.map(q =>
            prisma.stagedQuestion.create({
              data: {
                data: { ...q, type: body.type, points: 1 },
                source: 'ai_generated',
                status: 'PENDING',
                aiNotes: `Generated by ${body.model}`,
              },
            })
          )
        )

        await prisma.aiTask.update({
          where: { id: task.id },
          data: { status: 'done', result: staged as any, completedAt: new Date() },
        })
      } catch (err: any) {
        await prisma.aiTask.update({
          where: { id: task.id },
          data: { status: 'failed', error: err.message, completedAt: new Date() },
        })
      }
    })()

    return c.json({ taskId: task.id, message: 'Generation started' }, 202)
  }
)

// AI QA: fill missing fields for a question
app.post(
  '/qa-fill/:questionId',
  zValidator('json', z.object({ model: z.string() })),
  async (c) => {
    if (!process.env.OPEN_ROUTER_API_KEY) {
      return c.json({ error: 'OPEN_ROUTER_API_KEY not configured' }, 503)
    }

    const question = await prisma.question.findUnique({
      where: { id: c.req.param('questionId') },
      include: { answers: true },
    })
    if (!question) return c.json({ error: 'Not found' }, 404)

    const { model } = c.req.valid('json')
    const task = await prisma.aiTask.create({
      data: { type: 'qa_fill', status: 'running', model, prompt: question.id },
    })

    ;(async () => {
      try {
        const prompt = `Given this trivia question, suggest values for any missing fields.
Question: "${question.text}"
Answers: ${question.answers.map(a => a.text).join(', ')}
Current category: ${question.category ?? 'MISSING'}
Current subCategory: ${question.subCategory ?? 'MISSING'}
Current difficulty: ${question.difficulty}

Respond with a JSON object with only the fields that need updating:
{"category": "...", "subCategory": "...", "difficulty": "EASY|MEDIUM|HARD"}`

        const content = await openrouterChat(model, [{ role: 'user', content: prompt }])
        const jsonMatch = content.match(/\{[\s\S]*\}/)
        if (!jsonMatch) throw new Error('No JSON found')
        const suggestions = JSON.parse(jsonMatch[0])

        await prisma.aiTask.update({
          where: { id: task.id },
          data: { status: 'done', result: suggestions, completedAt: new Date() },
        })
      } catch (err: any) {
        await prisma.aiTask.update({
          where: { id: task.id },
          data: { status: 'failed', error: err.message, completedAt: new Date() },
        })
      }
    })()

    return c.json({ taskId: task.id }, 202)
  }
)

// AI semantic duplicate check
app.post(
  '/semantic-duplicate',
  zValidator('json', z.object({ model: z.string(), questionId: z.string() })),
  async (c) => {
    if (!process.env.OPEN_ROUTER_API_KEY) {
      return c.json({ error: 'OPEN_ROUTER_API_KEY not configured' }, 503)
    }

    const { model, questionId } = c.req.valid('json')
    const question = await prisma.question.findUnique({ where: { id: questionId } })
    if (!question) return c.json({ error: 'Not found' }, 404)

    // Get candidates from traditional duplicate detection first
    const candidates = await runDuplicateDetection(question.text, questionId)
    if (candidates.length === 0) return c.json({ duplicates: [] })

    const task = await prisma.aiTask.create({
      data: { type: 'semantic_duplicate', status: 'running', model, prompt: questionId },
    })

    ;(async () => {
      try {
        const candidateTexts = candidates.slice(0, 10).map((c: any, i: number) =>
          `${i + 1}. [${c.id}] "${c.text}" (score: ${c.score})`
        ).join('\n')

        const prompt = `Are any of these trivia questions semantically equivalent to or duplicates of the target question?

Target: "${question.text}"

Candidates:
${candidateTexts}

Respond with JSON: {"duplicates": [{"id": "...", "reason": "..."}]}`

        const content = await openrouterChat(model, [{ role: 'user', content: prompt }])
        const jsonMatch = content.match(/\{[\s\S]*\}/)
        if (!jsonMatch) throw new Error('No JSON found')
        const result = JSON.parse(jsonMatch[0])

        await prisma.aiTask.update({
          where: { id: task.id },
          data: { status: 'done', result, completedAt: new Date() },
        })
      } catch (err: any) {
        await prisma.aiTask.update({
          where: { id: task.id },
          data: { status: 'failed', error: err.message, completedAt: new Date() },
        })
      }
    })()

    return c.json({ taskId: task.id }, 202)
  }
)

export default app
